version: 0.2

phases:
    install:
        commands:
            - echo Install started on `date`
            - add-apt-repository ppa:ondrej/php
            - apt-get update
            - apt-get install -y php7.1-zip php7.1-gd
    pre_build:
        commands:
            - composer install --no-dev -o
            - cd ~/webroot/grav
            - bin/grav install
    build:
        commands:
            - echo Build started on `date`
            - composer test
